In [1]:
# modules we'll use
import pandas as pd
import numpy as np

In [2]:
nfl_data=pd.read_csv('train.csv.zip')

C:\Users\bruno\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (47) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
nfl_data.head()

,GameId,PlayId,Team,X,Y,S,A,Dis,Orientation,Dir,...,Week,Stadium,Location,StadiumType,Turf,GameWeather,Temperature,Humidity,WindSpeed,WindDirection
0,2017090700,20170907000118,away,73.91,34.84,1.69,1.13,0.40,81.99,177.18,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
1,2017090700,20170907000118,away,74.67,32.64,0.42,1.35,0.01,27.61,198.70,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
2,2017090700,20170907000118,away,74.00,33.20,1.22,0.59,0.31,3.01,202.73,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
3,2017090700,20170907000118,away,71.46,27.70,0.42,0.54,0.02,359.77,105.64,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
4,2017090700,20170907000118,away,69.32,35.42,1.82,2.43,0.16,12.63,164.31,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW

In [4]:
nfl_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682154 entries, 0 to 682153
Data columns (total 49 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   GameId                  682154 non-null  int64
 1   PlayId                  682154 non-null  int64
 2   Team                    682154 non-null  object
 3   X                       682154 non-null  float64
 4   Y                       682154 non-null  float64
 5   S                       682154 non-null  float64
 6   A                       682154 non-null  float64
 7   Dis                     682154 non-null  float64
 8   Orientation             682131 non-null  float64
 9   Dir                     682126 non-null  float64
 10  NflId                   682154 non-null  int64
 11  DisplayName             682154 non-null  object
 12  JerseyNumber            682154 non-null  int64
 13  Season                  682154 non-null  int64
 14  YardLine                682154 non-null  int64
 15  Quarter                 682154 non-null  int64
 16  GameClock               682154 non-null  object
 17  PossessionTeam          682154 non-null  object
 18  Down                    682154 non-null  int64
 19  Distance                682154 non-null  int64
 20  FieldPosition           673552 non-null  object
 21  HomeScoreBeforePlay     682154 non-null  int64
 22  VisitorScoreBeforePlay  682154 non-null  int64
 23  NflIdRusher             682154 non-null  int64
 24  OffenseFormation        682066 non-null  object
 25  OffensePersonnel        682154 non-null  object
 26  DefendersInTheBox       682132 non-null  float64
 27  DefensePersonnel        682154 non-null  object
 28  PlayDirection           682154 non-null  object
 29  TimeHandoff             682154 non-null  object
 30  TimeSnap                682154 non-null  object
 31  Yards                   682154 non-null  int64
 32  PlayerHeight            682154 non-null  object
 33  PlayerWeight            682154 non-null  int64
 34  PlayerBirthDate         682154 non-null  object
 35  PlayerCollegeName       682154 non-null  object
 36  Position                682154 non-null  object
 37  HomeTeamAbbr            682154 non-null  object
 38  VisitorTeamAbbr         682154 non-null  object
 39  Week                    682154 non-null  int64
 40  Stadium                 682154 non-null  object
 41  Location                682154 non-null  object
 42  StadiumType             640464 non-null  object
 43  Turf                    682154 non-null  object
 44  GameWeather             621984 non-null  object
 45  Temperature             618508 non-null  float64
 46  Humidity                675994 non-null  float64
 47  WindSpeed               590282 non-null  object
 48  WindDirection           577478 non-null  object
dtypes: float64(10), int64(15), object(24)
memory usage: 255.0+ MB

In [5]:
# set seed for reproducibility
np.random.seed(0)

In [6]:
# get the number of missing data points per column
missing_values_count = nfl_data.isnull().sum()

In [7]:
missing_values_count

GameId                         0
PlayId                         0
Team                           0
X                              0
Y                              0
S                              0
A                              0
Dis                            0
Orientation                   23
Dir                           28
NflId                          0
DisplayName                    0
JerseyNumber                   0
Season                         0
YardLine                       0
Quarter                        0
GameClock                      0
PossessionTeam                 0
Down                           0
Distance                       0
FieldPosition               8602
HomeScoreBeforePlay            0
VisitorScoreBeforePlay         0
NflIdRusher                    0
OffenseFormation              88
OffensePersonnel               0
DefendersInTheBox             22
DefensePersonnel               0
PlayDirection                  0
TimeHandoff                    0
TimeSnap                       0
Yards                          0
PlayerHeight                   0
PlayerWeight                   0
PlayerBirthDate                0
PlayerCollegeName              0
Position                       0
HomeTeamAbbr                   0
VisitorTeamAbbr                0
Week                           0
Stadium                        0
Location                       0
StadiumType                41690
Turf                           0
GameWeather                60170
Temperature                63646
Humidity                    6160
WindSpeed                  91872
WindDirection             104676
dtype: int64

In [8]:
# look at the # of missing points in the first ten columns
missing_values_count[0:10]

GameId          0
PlayId          0
Team            0
X               0
Y               0
S               0
A               0
Dis             0
Orientation    23
Dir            28
dtype: int64

In [9]:
# how many total missing values do we have?
total_cells = np.product(nfl_data.shape)
total_missing = missing_values_count.sum()

In [10]:
total_cells

33425546

In [11]:
total_missing

376977

In [12]:
# percent of data that is missing
percent_missing = (total_missing/total_cells) * 100
print(percent_missing)

1.1278110460783497

Wow, almost a quarter of the cells in this dataset are empty! In the next step, we're going to take a closer look at some of the columns with missing values and try to figure out what might be going on with them.

In [13]:
# look at the # of missing points in the first ten columns
missing_values_count[0:10]

GameId          0
PlayId          0
Team            0
X               0
Y               0
S               0
A               0
Dis             0
Orientation    23
Dir            28
dtype: int64

In [14]:
# remove all the rows that contain a missing value
nfl_data.dropna()

,GameId,PlayId,Team,X,Y,S,A,Dis,Orientation,Dir,...,Week,Stadium,Location,StadiumType,Turf,GameWeather,Temperature,Humidity,WindSpeed,WindDirection
0,2017090700,20170907000118,away,73.91,34.84,1.69,1.13,0.40,81.99,177.18,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
1,2017090700,20170907000118,away,74.67,32.64,0.42,1.35,0.01,27.61,198.70,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
2,2017090700,20170907000118,away,74.00,33.20,1.22,0.59,0.31,3.01,202.73,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
3,2017090700,20170907000118,away,71.46,27.70,0.42,0.54,0.02,359.77,105.64,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
4,2017090700,20170907000118,away,69.32,35.42,1.82,2.43,0.16,12.63,164.31,...,1,Gillette Stadium,"Foxborough, MA",Outdoor,Field Turf,Clear and warm,63.0,77.0,8,SW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682149,2019112500,20191125003789,home,69.58,31.33,4.19,1.33,0.43,92.32,20.94,...,12,Los Angeles Memorial Coliseum,"Los Angeles, CA",Outdoor,Grass,Clear,62.0,64.0,5,WSW
682150,2019112500,20191125003789,home,72.16,25.09,1.01,1.40,0.08,65.83,76.48,...,12,Los Angeles Memorial Coliseum,"Los Angeles, CA",Outdoor,Grass,Clear,62.0,64.0,5,WSW
682151,2019112500,20191125003789,home,72.23,31.95,1.75,0.68,0.17,93.99,90.26,...,12,Los Angeles Memorial Coliseum,"Los Angeles, CA",Outdoor,Grass,Clear,62.0,64.0,5,WSW
682152,2019112500,20191125003789,home,72.08,26.74,0.70,1.59,0.07,61.47,48.34,...,12,Los Angeles Memorial Coliseum,"Los Angeles, CA",Outdoor,Grass,Clear,62.0,64.0,5,WSW
682153,2019112500,20191125003789,home,68.11,24.67,4.71,1.30,0.47,48.28,27.89,...,12,Los Angeles Memorial Coliseum,"Los Angeles, CA",Outdoor,Grass,Clear,62.0,64.0,5,WSW

In [15]:
# remove all columns with at least one missing value
columns_with_na_dropped = nfl_data.dropna(axis=1)
columns_with_na_dropped.head()

,GameId,PlayId,Team,X,Y,S,A,Dis,NflId,DisplayName,...,PlayerWeight,PlayerBirthDate,PlayerCollegeName,Position,HomeTeamAbbr,VisitorTeamAbbr,Week,Stadium,Location,Turf
0,2017090700,20170907000118,away,73.91,34.84,1.69,1.13,0.40,496723,Eric Berry,...,212,12/29/1988,Tennessee,SS,NE,KC,1,Gillette Stadium,"Foxborough, MA",Field Turf
1,2017090700,20170907000118,away,74.67,32.64,0.42,1.35,0.01,2495116,Allen Bailey,...,288,03/25/1989,Miami,DE,NE,KC,1,Gillette Stadium,"Foxborough, MA",Field Turf
2,2017090700,20170907000118,away,74.00,33.20,1.22,0.59,0.31,2495493,Justin Houston,...,270,01/21/1989,Georgia,DE,NE,KC,1,Gillette Stadium,"Foxborough, MA",Field Turf
3,2017090700,20170907000118,away,71.46,27.70,0.42,0.54,0.02,2506353,Derrick Johnson,...,245,11/22/1982,Texas,ILB,NE,KC,1,Gillette Stadium,"Foxborough, MA",Field Turf
4,2017090700,20170907000118,away,69.32,35.42,1.82,2.43,0.16,2530794,Ron Parker,...,206,08/17/1987,Newberry,FS,NE,KC,1,Gillette Stadium,"Foxborough, MA",Field Turf

In [16]:
# just how much data did we lose?
print("Columns in original dataset: %d \n" % nfl_data.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_dropped.shape[1])

Columns in original dataset: 49

Columns with na's dropped: 38

We've lost quite a bit of data, but at this point we have successfully removed all the NaN's from our data.

In [17]:
# get a small subset of the NFL dataset
subset_nfl_data = nfl_data.loc[:, 'X':'PlayerWeight'].head()
subset_nfl_data

,X,Y,S,A,Dis,Orientation,Dir,NflId,DisplayName,JerseyNumber,...,OffenseFormation,OffensePersonnel,DefendersInTheBox,DefensePersonnel,PlayDirection,TimeHandoff,TimeSnap,Yards,PlayerHeight,PlayerWeight
0,73.91,34.84,1.69,1.13,0.40,81.99,177.18,496723,Eric Berry,29,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-0,212
1,74.67,32.64,0.42,1.35,0.01,27.61,198.70,2495116,Allen Bailey,97,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,288
2,74.00,33.20,1.22,0.59,0.31,3.01,202.73,2495493,Justin Houston,50,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,270
3,71.46,27.70,0.42,0.54,0.02,359.77,105.64,2506353,Derrick Johnson,56,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,245
4,69.32,35.42,1.82,2.43,0.16,12.63,164.31,2530794,Ron Parker,38,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-0,206

In [18]:
# replace all NA's with 0
subset_nfl_data.fillna(0)

,X,Y,S,A,Dis,Orientation,Dir,NflId,DisplayName,JerseyNumber,...,OffenseFormation,OffensePersonnel,DefendersInTheBox,DefensePersonnel,PlayDirection,TimeHandoff,TimeSnap,Yards,PlayerHeight,PlayerWeight
0,73.91,34.84,1.69,1.13,0.40,81.99,177.18,496723,Eric Berry,29,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-0,212
1,74.67,32.64,0.42,1.35,0.01,27.61,198.70,2495116,Allen Bailey,97,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,288
2,74.00,33.20,1.22,0.59,0.31,3.01,202.73,2495493,Justin Houston,50,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,270
3,71.46,27.70,0.42,0.54,0.02,359.77,105.64,2506353,Derrick Johnson,56,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,245
4,69.32,35.42,1.82,2.43,0.16,12.63,164.31,2530794,Ron Parker,38,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-0,206

In [19]:
# replace all NA's the value that comes directly after it in the same column, 
# then replace all the remaining na's with 0
subset_nfl_data.fillna(method='bfill', axis=0).fillna(0)

,X,Y,S,A,Dis,Orientation,Dir,NflId,DisplayName,JerseyNumber,...,OffenseFormation,OffensePersonnel,DefendersInTheBox,DefensePersonnel,PlayDirection,TimeHandoff,TimeSnap,Yards,PlayerHeight,PlayerWeight
0,73.91,34.84,1.69,1.13,0.40,81.99,177.18,496723,Eric Berry,29,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-0,212
1,74.67,32.64,0.42,1.35,0.01,27.61,198.70,2495116,Allen Bailey,97,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,288
2,74.00,33.20,1.22,0.59,0.31,3.01,202.73,2495493,Justin Houston,50,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,270
3,71.46,27.70,0.42,0.54,0.02,359.77,105.64,2506353,Derrick Johnson,56,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-3,245
4,69.32,35.42,1.82,2.43,0.16,12.63,164.31,2530794,Ron Parker,38,...,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",left,2017-09-08T00:44:06.000Z,2017-09-08T00:44:05.000Z,8,6-0,206